@baseUrl = http://localhost:3000
@authToken = {{authenticate.response.body.access_token}}

# @name create_pessoa
POST {{baseUrl}}/pessoas
Content-Type: application/json

{
  "nome": "Alexandre teste 1",
  "email": "alexandre@gmail.com.br",
  "senha": "123456",
  "cargo": "GERENTE"
}

###

# @name authenticate
POST {{baseUrl}}/login
Content-Type: application/json

{
  "email": "alexandre@gmail.com.br",
  "senha": "123456"
}

###

# @name create_fornecedores
POST {{baseUrl}}/fornecedores
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "nome": "Alexandre Fornecedor 1",
  "cnpj": "512505021000125"
}

###

# @name get_fornecedores
GET {{baseUrl}}/fornecedores
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name create_fornecedores
PUT {{baseUrl}}/fornecedores/1
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "nome": "Alexandre Fornecedor 1",
  "cnpj": "512505021"
}

###

# @name delete_fornecedores
DELETE {{baseUrl}}/fornecedores/1
Content-Type: application/json
Authorization: Bearer {{authToken}}
